BCA-Team/Buildcraft-Additions

src/main/java/buildcraftAdditions/client/gui/gui/GuiBase.java
src/main/java/buildcraftAdditions/client/gui/gui/GuiCoolingTower.java
src/main/java/buildcraftAdditions/client/gui/gui/GuiRefinery.java
src/main/java/buildcraftAdditions/client/gui/widgets/WidgetBase.java
src/main/java/buildcraftAdditions/client/gui/widgets/WidgetFluidTank.java
src/main/java/buildcraftAdditions/proxy/ClientProxy.java
src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java
src/main/java/buildcraftAdditions/utils/RenderUtils.java

Some GUI improvements what should make the use of the base GUI a lot more generic and easier

---

build.gradle
gradle.properties

Added Minetweaker dependency

---

src/main/java/buildcraftAdditions/BuildcraftAdditions.java
src/main/java/buildcraftAdditions/creative/TabBCAdditions.java
src/main/java/buildcraftAdditions/creative/TabCanisters.java
src/main/java/buildcraftAdditions/creative/TabDusts.java
src/main/java/buildcraftAdditions/items/BatteryBase.java
src/main/java/buildcraftAdditions/items/ItemCanister.java
src/main/java/buildcraftAdditions/items/ItemDust.java
src/main/java/buildcraftAdditions/nei/NEIConfig.java
src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java
src/main/resources/assets/bcadditions/lang/en_US.lang

Added creative tabs for Dusts and Canisters and display all filled canisters and power capsules in the creative menu and NEI

---

src/main/java/buildcraftAdditions/blocks/multiBlocks/BlockItemSorter.java
src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java
src/main/java/buildcraftAdditions/reference/Variables.java
src/main/java/buildcraftAdditions/tileEntities/TileItemSorter.java
src/main/java/buildcraftAdditions/utils/Utils.java
src/main/resources/assets/bcadditions/lang/en_US.lang

already PRing so that I don't cause merge conflicts later on.

Added the basic itemSorter block

---

src/main/java/buildcraftAdditions/ModIntegration/ModIntegration.java

Added a way to use the Kinetic capsules as a flux modifier in Tinkers Construct

---

src/main/java/buildcraftAdditions/tileEntities/TileKineticDuster.java
src/main/java/buildcraftAdditions/tileEntities/TileSemiAutomaticDuster.java

Just added the EnumColor parameter there. It is null, I tested it and it works.

Updated call of deprecated method injectItem

---

src/main/java/buildcraftAdditions/BuildcraftAdditions.java
src/main/java/buildcraftAdditions/blocks/FluidBlockBase.java
src/main/java/buildcraftAdditions/core/BucketHandler.java
src/main/java/buildcraftAdditions/core/EventListener.java
src/main/java/buildcraftAdditions/items/ItemBucketBCA.java
src/main/java/buildcraftAdditions/utils/RefineryRecipeConverter.java
src/main/resources/assets/bcadditions/lang/en_US.lang

Still needs textures or a renderer.

Add gas buckets with dynamic localization and made the gas fluid localization dynamic.

---

src/main/java/buildcraftAdditions/client/gui/gui/GuiHandler.java
src/main/java/buildcraftAdditions/items/Tools/ItemPipeColoringTool.java

title says it all, someone added a @SideOnly(Side.CLIENT) annotation to the GuiHandler class which caused the server to crash on startup. was it you @iTitus ?

Fix some server crashes

---

src/main/java/buildcraftAdditions/blocks/BlockKineticEnergyBufferTier1.java
src/main/java/buildcraftAdditions/client/gui/gui/GuiMachineConfigurator.java
src/main/java/buildcraftAdditions/core/EventListener.java
src/main/java/buildcraftAdditions/creative/TabBCAdditions.java
src/main/java/buildcraftAdditions/creative/TabCanisters.java
src/main/java/buildcraftAdditions/creative/TabDusts.java
src/main/java/buildcraftAdditions/networking/MessageConfiguration.java
src/main/java/buildcraftAdditions/tileEntities/Bases/TileDusterWithConfigurableOutput.java
src/main/java/buildcraftAdditions/tileEntities/Bases/TileKineticEnergyBufferBase.java
src/main/java/buildcraftAdditions/tileEntities/TileKEBT2.java
src/main/java/buildcraftAdditions/tileEntities/TileKEBT3.java
src/main/java/buildcraftAdditions/tileEntities/TileKineticDuster.java
src/main/java/buildcraftAdditions/tileEntities/TileKineticEnergyBufferTier1.java
src/main/java/buildcraftAdditions/tileEntities/TileSemiAutomaticDuster.java
src/main/java/buildcraftAdditions/utils/EnumPriority.java
src/main/java/buildcraftAdditions/utils/EnumSideStatus.java
src/main/java/buildcraftAdditions/utils/IConfigurableOutput.java
src/main/java/buildcraftAdditions/utils/SideConfiguration.java
src/main/java/buildcraftAdditions/utils/Utils.java
src/main/resources/assets/bcadditions/lang/en_US.lang

Fixed the pick block of the Creative KEB.
Fixed not stacking KEBs after wrench pickup.
Added swing animation for the pickup.
Added "Configured" tooltip if the KEB item has a NBT tag.
Added search bars to the Dust and Canister tab.
Added the empty canisters to the main tab.

Refractored the Side Configuration system.

---

src/main/java/buildcraftAdditions/ModIntegration/Buildcraft/BuildcraftIntegration.java

this should be the final commit for the Sort-O-Tron except if some bugs turn up...

Added Sort-O-Tron and Coloring Tool recipes

---

src/main/java/buildcraftAdditions/networking/MessageByteBuff.java
src/main/java/buildcraftAdditions/tileEntities/TileCoolingTower.java
src/main/java/buildcraftAdditions/tileEntities/TileRefinery.java
src/main/java/buildcraftAdditions/tileEntities/varHelpers/Upgrades.java
src/main/java/buildcraftAdditions/utils/fluids/CoolantTank.java

I still need your help on how to actually enable the adding of upgrades.
The other changes are fixes for diverse crash bugs I stumbled across.

Added upgrades support to the cooling tower and the refinery.

---

src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java

http://openeye.openmods.info/crashes/1df4d7a70b4332d1f1ed95cba2884f40

Fixed OpenEye report related to TE registration.

---

src/main/java/buildcraftAdditions/BuildcraftAdditions.java
src/main/java/buildcraftAdditions/ModIntegration/Buildcraft/BuildcraftIntegration.java
src/main/java/buildcraftAdditions/ModIntegration/ModIntegration.java
src/main/java/buildcraftAdditions/blocks/BlockItemSorter.java
src/main/java/buildcraftAdditions/client/gui/SlotItemSorter.java
src/main/java/buildcraftAdditions/client/gui/SlotPhantom.java
src/main/java/buildcraftAdditions/client/gui/containers/ContainerItemSorter.java
src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java
src/main/java/buildcraftAdditions/tileEntities/TileItemSorter.java

some bugs has been fixed and with the new api changes in BC 6.4 it might be time to release a 2.0.1. Also because there are a lot of bugfixes in here already that haven't been released

Added list support and some small fixes for the itemSorter

---

src/main/java/buildcraftAdditions/ModIntegration/imc/IMCHandler.java
src/main/java/buildcraftAdditions/blocks/BlockItemSorter.java
src/main/java/buildcraftAdditions/client/gui/SlotItemSorter.java
src/main/java/buildcraftAdditions/client/gui/containers/ContainerItemSorter.java
src/main/java/buildcraftAdditions/core/Logger.java
src/main/java/buildcraftAdditions/items/dust/DustManager.java

Added IMC messages for adding and removing dusts.

---

src/main/java/buildcraftAdditions/tileEntities/TileBasicCoil.java
src/main/resources/assets/bcadditions/lang/en_US.lang

Diverse fixes.

---

src/main/java/buildcraftAdditions/ModIntegration/Buildcraft/BuildcraftIntegration.java
src/main/java/buildcraftAdditions/blocks/BlockKineticEnergyBufferTier1.java
src/main/java/buildcraftAdditions/inventories/slots/SlotBattery.java
src/main/java/buildcraftAdditions/items/itemBlocks/ItemBlockKEB.java

made the T1 KEB an IEnergyContainerItem, this way it can be charged in the charging station and be used as a battery for tools.

---

src/main/java/buildcraftAdditions/config/ConfigGui.java
src/main/java/buildcraftAdditions/config/ConfigurationHandler.java
src/main/java/buildcraftAdditions/tileEntities/TileCoolingTower.java
src/main/java/buildcraftAdditions/tileEntities/TileRefinery.java
src/main/resources/assets/bcadditions/lang/en_US.lang

Configurable Updates.

---

src/main/java/buildcraftAdditions/core/EventListener.java
src/main/java/buildcraftAdditions/entities/EntityLaserShot.java

Also: balance for IToolWrenches

Laser fix and possible fix for the wrench-clicking

---

src/main/java/buildcraftAdditions/inventories/containers/ContainerBase.java
src/main/java/buildcraftAdditions/inventories/containers/ContainerFluidicCompressor.java
src/main/java/buildcraftAdditions/inventories/containers/ContainerItemSorter.java

this should hopefully fix #341, but if I remember correctly I made the `redraw` function for this purpose

Containerfix

---

src/main/java/buildcraftAdditions/config/ConfigurationHandler.java
src/main/java/buildcraftAdditions/reference/ItemsAndBlocks.java

This is just a config option to give the user some more control or shut up the annoying person on a server that he doesn't want to use the multiblock. It is disabled by default though.

Added a config option to force enable the BC refinery

---

src/main/java/buildcraftAdditions/client/gui/GuiCoolingTower.java
src/main/java/buildcraftAdditions/client/gui/GuiRefinery.java

don't ask me how I noticed but I did :D

fix GUI size from Refinery and cooling tower being one pixel to small
